# Generated by Django 3.1.3 on 2020-12-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='has_reached_out',
            field=models.BooleanField(default=False),
        ),
    ]
