# Generated by Django 3.1.3 on 2020-12-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0004_event_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='grade_level',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
