# Generated by Django 3.1.3 on 2020-12-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0005_books_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
