# Generated by Django 3.1.3 on 2020-12-17 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pledge_donations', '0006_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='donation_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='events', to='pledge_donations.Books'),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
