# Generated by Django 3.1.3 on 2020-12-17 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0007_auto_20201217_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donations', to='pledge_donations.books'),
        ),
    ]
