# Generated by Django 3.1.3 on 2020-12-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0008_auto_20201217_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='volunteer_goal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
