# Generated by Django 3.1.3 on 2020-12-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0009_event_volunteer_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='books',
        ),
        migrations.AddField(
            model_name='donations',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donations', to='pledge_donations.books'),
        ),
        migrations.AddField(
            model_name='event',
            name='book_goal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
