# Generated by Django 3.1.3 on 2020-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0010_auto_20201218_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='book',
            new_name='books',
        ),
        migrations.AddField(
            model_name='donations',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donations',
            name='item_count',
            field=models.IntegerField(default=1),
        ),
    ]
