# Generated by Django 3.1.3 on 2020-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0012_auto_20201219_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.png', upload_to='events/'),
        ),
    ]
