# Generated by Django 3.1.3 on 2020-12-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledge_donations', '0014_auto_20201220_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='has_reached_out',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
